name: Build FFmpegKit

on:
  push:
    branches:
      - main

jobs:
  build:
    name: macos main on sonoma
    runs-on: macos-14
    # runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: arthenica/ffmpeg-kit
          path: ffmpeg

      - name: prerequisites
        run: brew install autoconf automake libtool pkg-config curl git cmake nasm tree

      - name: set up xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          echo "export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer" >> $GITHUB_ENV

      # - name: set up xcode
      #   run: echo "export DEVELOPER_DIR=/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh


      # macOS
      - name: run the build script (macOS)
        working-directory: ./ffmpeg
        run: ./macos.sh --xcframework --enable-macos-audiotoolbox --enable-macos-avfoundation --enable-macos-bzip2 --enable-macos-coreimage --enable-macos-libiconv --enable-macos-opencl --enable-macos-opengl --enable-macos-videotoolbox --enable-macos-zlib

      - name: print build logs
        if: ${{ always() }}
        working-directory: ./ffmpeg
        run: cat build.log

      - name: print ffbuild logs
        working-directory: ./ffmpeg
        if: ${{ failure() }}
        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'

        
      # iOS
      - name: run the build script (iOS)
        working-directory: ./ffmpeg
        run: ./ios.sh --xcframework --enable-ios-audiotoolbox --enable-ios-avfoundation --enable-ios-bzip2 --enable-ios-libiconv --enable-ios-videotoolbox --enable-ios-zlib

      - name: print build logs
        if: ${{ always() }}
        working-directory: ./ffmpeg
        run: cat build.log

      - name: print ffbuild logs
        working-directory: ./ffmpeg
        if: ${{ failure() }}
        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'

      - name: print ./ffmpeg/prebuilt/
        working-directory: ./ffmpeg/prebuilt/
        run: |
          ls -al
          tree -L 3

      # - name: Verify XCFramework
      #   working-directory: ./ffmpeg
      #   run: lipo -info ios/ffmpeg-kit.xcframework/macos-x86_64_arm64/libffmpeg.dylib

      - name: remove ./ffmpeg/.git
        run: rm -rf ./ffmpeg/.git

      - name: Copy all .xcframework directories
        run: |
          mkdir -p ./ffmpeg-kit/macos
          find ./ffmpeg/prebuilt/bundle-apple-xcframework-macos/ -type d -name "*.xcframework" -exec cp -R {} ./ffmpeg-kit/macos/ \;
          mkdir -p ./ffmpeg-kit/ios
          find ./ffmpeg/prebuilt/bundle-apple-xcframework-ios/ -type d -name "*.xcframework" -exec cp -R {} ./ffmpeg-kit/ios/ \;

      - name: print ./ffmpeg-kit/macos
        working-directory: ./ffmpeg-kit/macos
        run: ls -al

      - name: print ./ffmpeg-kit/ios
        working-directory: ./ffmpeg-kit/ios
        run: ls -al

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add -f ./ffmpeg-kit/macos
          git add -f ./ffmpeg-kit/ios
          git commit -m "Update xcframeworks" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}